"""empty message

Revision ID: 5a8f9191d664
Revises: 2f1e3efdcbf1
Create Date: 2023-02-09 15:39:47.459264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8f9191d664'
down_revision = '2f1e3efdcbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_types_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('pokemon_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('moves', sa.String(), nullable=False),
    sa.Column('encounter_rate', sa.Float(), nullable=False),
    sa.Column('catch_rate', sa.Float(), nullable=False),
    sa.Column('captured', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['pokemon_types_table.type'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('items_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('pokemonId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemonId'], ['pokemon_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items')
    op.drop_table('pokemon_types')
    op.drop_table('pokemon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=False),
    sa.Column('attack', sa.INTEGER(), nullable=False),
    sa.Column('defense', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('moves', sa.VARCHAR(), nullable=False),
    sa.Column('captured', sa.BOOLEAN(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.Column('encounter_rate', sa.FLOAT(), nullable=False),
    sa.Column('catch_rate', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('number')
    )
    op.create_table('pokemon_types',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('happiness', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('pokemonId', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['pokemonId'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items_table')
    op.drop_table('pokemon_table')
    op.drop_table('pokemon_types_table')
    # ### end Alembic commands ###
