"""add seeders

Revision ID: 2f1e3efdcbf1
Revises: e641228827de
Create Date: 2023-02-09 13:52:37.734191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1e3efdcbf1'
down_revision = 'e641228827de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.drop_column('imageUrl')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('encounter_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('catch_rate', sa.Float(), nullable=False))
        batch_op.drop_column('catchRate')
        batch_op.drop_column('encounterRate')
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('encounterRate', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('catchRate', sa.FLOAT(), nullable=False))
        batch_op.drop_column('catch_rate')
        batch_op.drop_column('encounter_rate')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
